"""sprint 8 mother info + assignment weekly_periods

Revision ID: 58bd0c633c45
Revises: e1d9f354c17d
Create Date: 2026-07-09 10:55:43.632580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58bd0c633c45'
down_revision = 'e1d9f354c17d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekly_periods', sa.Integer(), server_default='1', nullable=False))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mother_name', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('mother_phone', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('mother_phone')
        batch_op.drop_column('mother_name')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('weekly_periods')

    # ### end Alembic commands ###
