"""sprint 6 portal api material

Revision ID: e1d9f354c17d
Revises: 1e2fe84b9653
Create Date: 2026-06-23 20:48:17.143039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1d9f354c17d'
down_revision = '1e2fe84b9653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['year_id'], ['academic_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materials_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_teacher_id'), ['teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_year_id'), ['year_id'], unique=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_students_parent_user_id'), ['parent_user_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['parent_user_id'], ['id'])

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_teachers_user_id'), ['user_id'], unique=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_teachers_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_students_parent_user_id'))
        batch_op.drop_column('parent_user_id')

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_year_id'))
        batch_op.drop_index(batch_op.f('ix_materials_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_materials_subject_id'))
        batch_op.drop_index(batch_op.f('ix_materials_section_id'))
        batch_op.drop_index(batch_op.f('ix_materials_school_id'))

    op.drop_table('materials')
    # ### end Alembic commands ###
