"""sprint 12: LMS tables — courses, lessons, assignments, quizzes, announcements

Revision ID: e360ab83c84a
Revises: a1b2c3d4e5f6
Create Date: 2026-09-14 07:46:34.111843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e360ab83c84a'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lms_announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lms_announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lms_announcements_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lms_announcements_section_id'), ['section_id'], unique=False)

    op.create_table('lms_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year_id', 'section_id', 'subject_id', name='uq_course_year_section_subject')
    )
    with op.batch_alter_table('lms_courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lms_courses_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lms_courses_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lms_courses_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lms_courses_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lms_courses_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('lms_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allow_late', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['lms_courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lms_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lms_assignments_course_id'), ['course_id'], unique=False)

    op.create_table('lms_lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['lms_courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lms_lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lms_lessons_course_id'), ['course_id'], unique=False)

    op.create_table('lms_quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('shuffle_questions', sa.Boolean(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['lms_courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lms_quizzes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lms_quizzes_course_id'), ['course_id'], unique=False)

    op.create_table('lms_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('points', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('correct_short', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['lms_quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lms_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lms_questions_quiz_id'), ['quiz_id'], unique=False)

    op.create_table('lms_quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('auto_graded', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['lms_quizzes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lms_quiz_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lms_quiz_attempts_quiz_id'), ['quiz_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lms_quiz_attempts_student_id'), ['student_id'], unique=False)

    op.create_table('lms_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('graded_by_id', sa.Integer(), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['lms_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['graded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'student_id', name='uq_submission_assignment_student')
    )
    with op.batch_alter_table('lms_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lms_submissions_assignment_id'), ['assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lms_submissions_student_id'), ['student_id'], unique=False)

    op.create_table('lms_choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['lms_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lms_choices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lms_choices_question_id'), ['question_id'], unique=False)

    op.create_table('lms_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('choice_id', sa.Integer(), nullable=True),
    sa.Column('text_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('awarded_points', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['lms_quiz_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['choice_id'], ['lms_choices.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['lms_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lms_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lms_answers_attempt_id'), ['attempt_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lms_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lms_answers_attempt_id'))

    op.drop_table('lms_answers')
    with op.batch_alter_table('lms_choices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lms_choices_question_id'))

    op.drop_table('lms_choices')
    with op.batch_alter_table('lms_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lms_submissions_student_id'))
        batch_op.drop_index(batch_op.f('ix_lms_submissions_assignment_id'))

    op.drop_table('lms_submissions')
    with op.batch_alter_table('lms_quiz_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lms_quiz_attempts_student_id'))
        batch_op.drop_index(batch_op.f('ix_lms_quiz_attempts_quiz_id'))

    op.drop_table('lms_quiz_attempts')
    with op.batch_alter_table('lms_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lms_questions_quiz_id'))

    op.drop_table('lms_questions')
    with op.batch_alter_table('lms_quizzes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lms_quizzes_course_id'))

    op.drop_table('lms_quizzes')
    with op.batch_alter_table('lms_lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lms_lessons_course_id'))

    op.drop_table('lms_lessons')
    with op.batch_alter_table('lms_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lms_assignments_course_id'))

    op.drop_table('lms_assignments')
    with op.batch_alter_table('lms_courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lms_courses_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_lms_courses_subject_id'))
        batch_op.drop_index(batch_op.f('ix_lms_courses_section_id'))
        batch_op.drop_index(batch_op.f('ix_lms_courses_school_id'))
        batch_op.drop_index(batch_op.f('ix_lms_courses_academic_year_id'))

    op.drop_table('lms_courses')
    with op.batch_alter_table('lms_announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lms_announcements_section_id'))
        batch_op.drop_index(batch_op.f('ix_lms_announcements_school_id'))

    op.drop_table('lms_announcements')
    # ### end Alembic commands ###
